// shellActions: imported feature APIs; state belongs to explicit application namespaces.
import {state as appState} from '../app/state.js';
import {authTab,landingNavTo,showAuthPage,showLandingPage} from './authentication.js';
import {toggleTheme} from './theme.js';
import {previewSelfie,sanitizeInput} from './inputValidation.js';
import {closePendingPanel,doLogin,doRegister,hidePasswordChecklist,openPrivacyNotice,openResendVerification,showPasswordChecklist,updatePasswordStrength} from './loginLockout.js';
import {closeForgotPassword,hideRecoveryPasswordChecklist,logout,openForgotPassword,sendPasswordResetEmail,showForgotStep,showRecoveryPasswordChecklist,submitNewPassword,updateRecoveryPasswordStrength} from './passwordRecovery.js';
import {handleIdFileChange,recheckNameMatch,sanitizeRegistrationId,updateRegistrationIdentityFields} from './documentScanner.js';
import {openCampusDatePicker} from './datePicker.js';
import {openCamera} from '../app/optional-features.js';
import {handleTopSearchKey,renderTopSearch,toggleSidebar} from './topbarAndNavigation.js';
import {openProfileDetails} from './accountSettings.js';
import {markAllRead,toggleNotifPanel} from './assistant.js';
import {registerNamedAction} from '../dependencies.js';
// Shell controls use registered lexical callbacks, never HTML inline JavaScript.

// Run side effects only after every feature's function exports are available.
export function initializeFeature(){
  registerNamedAction('shell-0',(event,element)=>{landingNavTo('home')});
  registerNamedAction('shell-1',(event,element)=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();landingNavTo('home')}});
  registerNamedAction('shell-2',(event,element)=>{landingNavTo('home')});
  registerNamedAction('shell-3',(event,element)=>{landingNavTo('services')});
  registerNamedAction('shell-4',(event,element)=>{landingNavTo('about')});
  registerNamedAction('shell-5',(event,element)=>{landingNavTo('contact')});
  registerNamedAction('shell-6',(event,element)=>{showAuthPage('login')});
  registerNamedAction('shell-7',(event,element)=>{document.querySelector('.landing-nav-links').classList.toggle('mobile-show')});
  registerNamedAction('shell-8',(event,element)=>{showAuthPage('login')});
  registerNamedAction('shell-9',(event,element)=>{showLandingPage()});
  registerNamedAction('shell-10',(event,element)=>{toggleTheme()});
  registerNamedAction('shell-11',(event,element)=>{authTab('login')});
  registerNamedAction('shell-12',(event,element)=>{authTab('reg')});
  registerNamedAction('shell-13',(event,element)=>{sanitizeInput(element,'password')});
  registerNamedAction('shell-14',(event,element)=>{if(event.key==='Enter')doLogin()});
  registerNamedAction('shell-15',(event,element)=>{openResendVerification();return false;});
  registerNamedAction('shell-16',(event,element)=>{openForgotPassword();return false;});
  registerNamedAction('shell-17',(event,element)=>{doLogin()});
  registerNamedAction('shell-18',(event,element)=>{sanitizeInput(element,'name');recheckNameMatch()});
  registerNamedAction('shell-19',(event,element)=>{sanitizeInput(element,'name');recheckNameMatch()});
  registerNamedAction('shell-20',(event,element)=>{sanitizeInput(element,'username')});
  registerNamedAction('shell-21',(event,element)=>{sanitizeInput(element,'email')});
  registerNamedAction('shell-22',(event,element)=>{showPasswordChecklist()});
  registerNamedAction('shell-23',(event,element)=>{sanitizeInput(element,'password');updatePasswordStrength()});
  registerNamedAction('shell-24',(event,element)=>{hidePasswordChecklist()});
  registerNamedAction('shell-25',(event,element)=>{sanitizeInput(element,'phone')});
  registerNamedAction('shell-26',(event,element)=>{updateRegistrationIdentityFields()});
  registerNamedAction('shell-27',(event,element)=>{sanitizeRegistrationId(element)});
  registerNamedAction('shell-28',(event,element)=>{openCampusDatePicker('r-dob','Select Date of Birth','',appState.clinicInformation.TODAY,'')});
  registerNamedAction('shell-29',(event,element)=>{document.getElementById('r-selfie-file').click()});
  registerNamedAction('shell-30',(event,element)=>{openCamera('selfie')});
  registerNamedAction('shell-31',(event,element)=>{previewSelfie(element)});
  registerNamedAction('shell-32',(event,element)=>{document.getElementById('r-id-file').click()});
  registerNamedAction('shell-33',(event,element)=>{handleIdFileChange(element)});
  registerNamedAction('shell-34',(event,element)=>{event.stopPropagation();openCamera('id')});
  registerNamedAction('shell-35',(event,element)=>{event.preventDefault();openPrivacyNotice()});
  registerNamedAction('shell-36',(event,element)=>{doRegister()});
  registerNamedAction('shell-37',(event,element)=>{openResendVerification(appState.loginLockout.pendingRegistrationEmail||'')});
  registerNamedAction('shell-38',(event,element)=>{closePendingPanel()});
  registerNamedAction('shell-39',(event,element)=>{sendPasswordResetEmail()});
  registerNamedAction('shell-40',(event,element)=>{closeForgotPassword()});
  registerNamedAction('shell-41',(event,element)=>{closeForgotPassword()});
  registerNamedAction('shell-42',(event,element)=>{showRecoveryPasswordChecklist()});
  registerNamedAction('shell-43',(event,element)=>{sanitizeInput(element,'password');updateRecoveryPasswordStrength()});
  registerNamedAction('shell-44',(event,element)=>{hideRecoveryPasswordChecklist()});
  registerNamedAction('shell-45',(event,element)=>{sanitizeInput(element,'password')});
  registerNamedAction('shell-46',(event,element)=>{submitNewPassword()});
  registerNamedAction('shell-47',(event,element)=>{showForgotStep(1)});
  registerNamedAction('shell-48',(event,element)=>{toggleSidebar(false)});
  registerNamedAction('shell-49',(event,element)=>{openProfileDetails()});
  registerNamedAction('shell-50',(event,element)=>{logout()});
  registerNamedAction('shell-51',(event,element)=>{toggleTheme()});
  registerNamedAction('shell-52',(event,element)=>{toggleSidebar()});
  registerNamedAction('shell-53',(event,element)=>{renderTopSearch(element.value)});
  registerNamedAction('shell-54',(event,element)=>{handleTopSearchKey(event)});
  registerNamedAction('shell-55',(event,element)=>{renderTopSearch(element.value)});
  registerNamedAction('shell-56',(event,element)=>{toggleNotifPanel()});
  registerNamedAction('shell-57',(event,element)=>{markAllRead()});
}
