// One state container per feature; auth and data have dedicated owners.
// Import this object to read/write live state without publishing bindings on window.
export const state={
  supabaseClient:{},
  data:{},
  dataServices:{},
  utilities:{},
  clinicInformation:{},
  auth:{},
  doctorPatients:{},
  persistence:{},
  auditAndBackups:{},
  theme:{},
  camera:{},
  documentScanner:{},
  assistant:{},
  authentication:{},
  loginLockout:{},
  sessionSecurity:{},
  topbarAndNavigation:{},
  navigationRaceProtection:{},
  issueReports:{},
  dashboardChartHelpers:{},
  workflowRequests:{},
  approvalQueue:{},
  messaging:{},
  reports:{},
  reportCharts:{},
  certificateService:{},
  calendar:{},
  datePicker:{},
  bookingForm:{},
  patientForm:{},
  inventoryForms:{},
  scheduleAndDrafts:{},
};
